# Generated by Django 5.1.1 on 2025-04-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
