# Generated by Django 5.1.1 on 2025-04-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_marca_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='producto',
        ),
        migrations.DeleteModel(
            name='AtributoProducto',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Variante',
        ),
    ]
