# Generated by Django 5.1.1 on 2025-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
