# Generated by Django 5.1.1 on 2025-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('productos', '0004_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementocarrito',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.variante'),
        ),
    ]
