# Generated by Django 5.1.1 on 2025-04-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='perfiles/default.png', null=True, upload_to='perfiles/'),
        ),
    ]
